# Generated by Django 5.0 on 2023-12-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teams',
        ),
    ]
